services:
  iliadstats:
    image: ghcr.io/eugeniomoro/iliadstats:latest
    ports:
      - "8000:8000"
    volumes:
      - ./secrets.json:/app/secrets.json
    environment:
      - PYTHONUNBUFFERED=1